package dev.bogwalk.models

enum class QuizMode {
    STUDYING, CHECKED, WAITING, CHOSEN
}

enum class MainState {
    ALL_DECKS, DECK_OVERVIEW, IN_QUESTION, IN_REVIEW, UPDATING_DECK, UPDATING_QUESTION, UPDATING_REVIEW
}